apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-02-26T15:15:09Z"
  generation: 1
  labels:
    app: reactjs-calculator-web
  name: reactjs-calculator-web
  namespace: default
  resourceVersion: "12379"
  uid: 6308eef8-1af9-4f38-abae-975dbb0c4065
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: reactjs-calculator-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reactjs-calculator-web
    spec:
      containers:
      - image: caprilespe/reactjs-calculator-web:v1
        imagePullPolicy: IfNotPresent
        name: reactjs-calculator-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-02-26T15:15:18Z"
    lastUpdateTime: "2022-02-26T15:15:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-02-26T15:15:09Z"
    lastUpdateTime: "2022-02-26T15:15:18Z"
    message: ReplicaSet "reactjs-calculator-web-6cdbb5d7c6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
